import google.generativeai as genai
import logging
import time
from google.api_core import exceptions as google_exceptions

# --- CUSTOM LOGGER SETUP ---
# 1. Get a custom logger
logger = logging.getLogger('synthesis_agent')
logger.setLevel(logging.INFO)

# 2. Create a handler
handler = logging.StreamHandler()

# 3. Create a custom formatter and set it for the handler
formatter = logging.Formatter('%(asctime)s - 🔵 SYNTH - %(message)s')
handler.setFormatter(formatter)

# 4. Add the handler to the logger
if not logger.handlers:
    logger.addHandler(handler)

# 5. Stop logger from propagating to the root logger
logger.propagate = False
# --- END CUSTOM LOGGER SETUP ---


def generate_investment_summary(
    ticker: str, 
    quantitative_analysis: str, 
    qualitative_analysis: dict, 
    valuation_analysis: dict,  # <--- NEW PARAMETER
    agent_config: dict
) -> str:
    """
    Generates a final, comprehensive investment summary using the Gemini model.
    Accepts an agent_config dictionary for API key and model names.
    """
    api_key = agent_config.get("GOOGLE_API_KEY")
    model_name = agent_config.get("HEAVY_MODEL_NAME", "gemini-1.5-flash") 

    if not api_key:
        msg = "Synthesis Agent Error: Google API Key is not configured."
        logger.error(msg)
        return msg

    # --- 1. Prepare Qualitative Summary ---
    if qualitative_analysis:
        qualitative_summary = f"""
        - Positives & Concerns (Latest Quarter): {qualitative_analysis.get('positives_and_concerns', 'N/A')}
        - Quarter-over-Quarter Comparison: {qualitative_analysis.get('qoq_comparison', 'N/A')}
        - Scuttlebutt Analysis (Management, Competition, Culture): {qualitative_analysis.get('scuttlebutt', 'N/A')}
        - SEBI Compliance Check: {qualitative_analysis.get('sebi_check', 'N/A')}
        """
    else:
        qualitative_summary = "Qualitative analysis was not performed or failed."
    
    # --- 2. Prepare Quantitative Summary ---
    if not quantitative_analysis:
        quantitative_analysis = "Quantitative analysis was not performed or failed."

    # --- 3. Prepare Valuation Summary (NEW) ---
    if valuation_analysis:
        # We extract the text content generated by the valuation agent
        val_content = valuation_analysis.get('content', 'Valuation analysis content missing.')
    else:
        val_content = "Valuation analysis was not performed."

    # --- 4. Construct Prompt ---
    prompt = f"""
    You are a senior investment analyst at a top-tier hedge fund. Your task is to synthesize the provided Quantitative, Qualitative, and Valuation analyses for the company **{ticker}** into a single, comprehensive, and actionable investment summary.

    The final report must be structured exactly as follows, using Markdown for formatting:

    ### Investment Thesis
    **This is the most critical section.** Provide a decisive conclusion: Buy, Sell, or Hold.
    * Triangulate the data: Does the *Financial Health* (Quant) and *Business Quality* (Qual) justify the current *Price* (Valuation)?
    * If the company is great but overvalued, say so. If it's a turnaround play with risks, be explicit.

    ## 1. Executive Summary
    A brief, high-level overview (3-4 sentences) summarizing the key findings across all three dimensions (Quant, Qual, Valuation).

    ## 2. Quantitative Analysis Summary
    Summarize the key takeaways from the quantitative analysis. Focus on trends in revenue, profitability, debt, and cash flow.

    ## 3. Qualitative Analysis Summary
    Summarize the key insights from the qualitative analysis. Focus on management's tone, competitive advantages (moat), industry trends, and any red flags from the scuttlebutt or SEBI check.

    ## 4. Valuation & Governance Analysis
    Summarize the relative valuation findings. 
    * Is the stock cheap, fair, or expensive compared to peers? 
    * **Crucial:** Highlight the "Promoter Pledge" status and the "PEG Ratio" verdict.
    * Mention if Free Cash Flow (FCF) supports the valuation.

    ## 5. SWOT Analysis
    Based on ALL the information provided, generate a SWOT analysis:
    - **Strengths:** Internal factors (e.g., strong margins, clean balance sheet, moat).
    - **Weaknesses:** Internal disadvantages (e.g., high debt, pledged shares, declining growth).
    - **Opportunities:** External factors (e.g., new markets, industry tailwinds).
    - **Threats:** External risks (e.g., aggressive competition, valuation contraction).

    ## 6. Key Monitorables 
    Conclude with a bulleted list of 3-4 key metrics or factors that an investor should monitor in the upcoming quarters. 

    ---
    **Disclaimer:** This report is AI-generated and is for informational purposes only. It does not constitute financial advice. Please conduct your own due diligence.
    ---

    Here is the data you need to synthesize:

    ### Quantitative Analysis Report:
    ```
    {quantitative_analysis}
    ```

    ### Qualitative Analysis Report:
    ```
    {qualitative_summary}
    ```

    ### Valuation Analysis Report:
    ```
    {val_content}
    ```
    """

    logger.info(f"Generating final investment summary for {ticker}...")
    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(model_name)
        
        # --- RETRY LOGIC ---
        max_retries = 3
        base_delay_seconds = 65 

        for attempt in range(max_retries):
            try:
                logger.info(f"Calling Gemini for synthesis of {ticker} (Attempt {attempt + 1})")
                response = model.generate_content(prompt)
                logger.info(f"Finished final analysis for {ticker}.")
                return response.text
            
            except (google_exceptions.ResourceExhausted, google_exceptions.TooManyRequests) as e:
                logger.warning(f"Rate limit hit for '{ticker}' synthesis: {e}. Waiting {base_delay_seconds}s to retry...")
                if attempt < max_retries - 1:
                    time.sleep(base_delay_seconds)
                else:
                    logger.error(f"Final attempt failed for '{ticker}' synthesis.")
                    return f"An error occurred during synthesis analysis for {ticker}: Rate limit exceeded. {str(e)}"
            
            except Exception as e:
                if "429" in str(e):
                     logger.warning(f"Rate limit (429) detected for '{ticker}' synthesis: {e}. Waiting {base_delay_seconds}s to retry...")
                     if attempt < max_retries - 1:
                        time.sleep(base_delay_seconds)
                     else:
                        return f"An error occurred during synthesis analysis for {ticker}: Rate limit exceeded. {str(e)}"
                else:
                    error_msg = f"An error occurred during synthesis analysis for {ticker}: {e}"
                    logger.error(error_msg)
                    return error_msg
        
        return f"An error occurred during synthesis analysis for {ticker} after {max_retries} attempts."

    except Exception as e:
        error_msg = f"A setup error occurred during synthesis analysis for {ticker}: {e}"
        logger.error(error_msg)
        return error_msg